### ISSUE TITLE
#Fixed - Modal não carrega as categorias quando vai adicionar uma transação

### ISSUE THREAD

**Issue by lazarobodevan** [lazarobodevan/Mabills#1]
Ao tentar adicionar uma nova transação, se houver a propriedade selected, as categorias não são carregadas e é lançado um erro no console.
```html
<select name="categories" class="dropdown"  (change)="setCategory($event)" >
                <option value="" >Selecione...</option>
                <option *ngFor="let opt of categories" 
                         value="{{opt._id}}" [selected]="(inputTransaction && opt) && (inputTransaction.categoryId._id === opt._id)">
                    {{opt.name}}
                </option>
</select>

```
O erro lançado é

> ERROR TypeError: Cannot read properties of undefined (reading '_id')
    at ModalComponent_option_22_Template (modal.component.html:18:56)
    at executeTemplate (core.mjs:10482:9)
    at refreshView (core.mjs:10367:13)
    at refreshEmbeddedViews (core.mjs:11380:17)
    at refreshView (core.mjs:10391:9)
    at refreshComponent (core.mjs:11426:13)
    at refreshChildComponents (core.mjs:10157:9)
    at refreshView (core.mjs:10417:13)
    at refreshEmbeddedViews (core.mjs:11380:17)
    at refreshView (core.mjs:10391:9)

O erro não acontece quando edita-se uma transação

**Comment by lazarobodevan** [comment]
Adicionado código na função getCategories no modal.component.ts para forçar a detecção de mudança e carregar as categorias ao adicionar uma nova transação.

`this.ref.detectChanges();`
